apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-modules-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/node-modules"
